### ISSUE TITLE
Half the outlets in the kitchen don't work

### ISSUE THREAD

**Issue by ianweller** [714warren/issues#1]
We think the GFCI circuit on the west side of the kitchen is to blame.

**Comment by ianweller** [comment]
This issue appears to be fixed. The Echo has been plugged into that set of outlets for a while now and was just able to add bread to the shopping list.

**Comment by streed** [comment]
[![ALEXA BREAD](https://img.youtube.com/vi/NE1-dKc6R_I/0.jpg)](https://www.youtube.com/watch?v=NE1-dKc6R_I)
