### ISSUE TITLE
Invasion.

### ISSUE THREAD

**Issue by streed** [714warren/issues#3]
@714warren/people-in-reed-s-room-that-shouldn-t-be you know.

**Comment by ianweller** [comment]
nah

**Comment by streed** [comment]
Reopened on the grounds that the invasion continues with the @714warren/people-in-reed-s-room-that-shouldn-t-be

**Comment by ianweller** [comment]
You're not even there!

Neither is anybody else for that matter

**Comment by streed** [comment]
We can finally close this.
